version: 2

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Static analysis checks
    - unused         # Check for unused code
    - misspell       # Finds commonly misspelled words
    - revive         # Drop-in replacement for golint

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters-settings:
  goimports:
    local-prefixes: github.com/RynoXLI/Wayfile
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
run:
  timeout: 5m
  skip-dirs:
    - gen
    - tmp
  skip-files:
    - ".*\\.pb\\.go$"
