// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute-schemas.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchema = `-- name: CreateSchema :one
INSERT INTO attribute_schemas (
    tag_id,
    json_schema
) VALUES (
    $1, $2
) RETURNING 
    tag_id,
    version,
    json_schema,
    created_at
`

func (q *Queries) CreateSchema(ctx context.Context, tagID pgtype.UUID, jsonSchema json.RawMessage) (AttributeSchema, error) {
	row := q.db.QueryRow(ctx, createSchema, tagID, jsonSchema)
	var i AttributeSchema
	err := row.Scan(
		&i.TagID,
		&i.Version,
		&i.JsonSchema,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSchemaByTagID = `-- name: GetLatestSchemaByTagID :one
SELECT 
    tag_id, 
    version,
    json_schema,
    created_at
FROM attribute_schemas
WHERE tag_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSchemaByTagID(ctx context.Context, tagID pgtype.UUID) (AttributeSchema, error) {
	row := q.db.QueryRow(ctx, getLatestSchemaByTagID, tagID)
	var i AttributeSchema
	err := row.Scan(
		&i.TagID,
		&i.Version,
		&i.JsonSchema,
		&i.CreatedAt,
	)
	return i, err
}

const getSchemas = `-- name: GetSchemas :many
WITH LATEST AS (
    SELECT tag_id, max(version) as latest_version 
    FROM attribute_schemas
    GROUP BY tag_id
)
SELECT 
    a.tag_id, 
    a.version,
    a.json_schema,
    a.created_at
FROM attribute_schemas a
JOIN LATEST l ON 
    a.tag_id = l.tag_id AND 
    a.version = l.latest_version
`

func (q *Queries) GetSchemas(ctx context.Context) ([]AttributeSchema, error) {
	rows, err := q.db.Query(ctx, getSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeSchema{}
	for rows.Next() {
		var i AttributeSchema
		if err := rows.Scan(
			&i.TagID,
			&i.Version,
			&i.JsonSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
