// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute-schemas.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchema = `-- name: CreateSchema :one
INSERT INTO attribute_schemas (
    tag_id,
    json_schema
) VALUES (
    $1, $2
) RETURNING 
    tag_id,
    version,
    json_schema,
    created_at
`

func (q *Queries) CreateSchema(ctx context.Context, tagID pgtype.UUID, jsonSchema json.RawMessage) (AttributeSchema, error) {
	row := q.db.QueryRow(ctx, createSchema, tagID, jsonSchema)
	var i AttributeSchema
	err := row.Scan(
		&i.TagID,
		&i.Version,
		&i.JsonSchema,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSchemaByTagID = `-- name: GetLatestSchemaByTagID :one
SELECT 
    tag_id, 
    version,
    json_schema,
    created_at
FROM attribute_schemas
WHERE tag_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSchemaByTagID(ctx context.Context, tagID pgtype.UUID) (AttributeSchema, error) {
	row := q.db.QueryRow(ctx, getLatestSchemaByTagID, tagID)
	var i AttributeSchema
	err := row.Scan(
		&i.TagID,
		&i.Version,
		&i.JsonSchema,
		&i.CreatedAt,
	)
	return i, err
}
