// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document-tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const associateTag = `-- name: AssociateTag :exec
INSERT INTO document_tags (
    document_id,
    tag_id,
    attributes
) VALUES (
    $1, $2, $3
)
`

func (q *Queries) AssociateTag(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID, attributes []byte) error {
	_, err := q.db.Exec(ctx, associateTag, documentID, tagID, attributes)
	return err
}

const getDocumentsByTagID = `-- name: GetDocumentsByTagID :many
SELECT dt.document_id, dt.attributes
FROM document_tags dt
WHERE dt.tag_id = $1
`

type GetDocumentsByTagIDRow struct {
	DocumentID pgtype.UUID `json:"document_id"`
	Attributes []byte      `json:"attributes"`
}

func (q *Queries) GetDocumentsByTagID(ctx context.Context, tagID pgtype.UUID) ([]GetDocumentsByTagIDRow, error) {
	rows, err := q.db.Query(ctx, getDocumentsByTagID, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentsByTagIDRow{}
	for rows.Next() {
		var i GetDocumentsByTagIDRow
		if err := rows.Scan(&i.DocumentID, &i.Attributes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByDocumentID = `-- name: GetTagsByDocumentID :many
SELECT dt.tag_id, dt.attributes
FROM document_tags dt
WHERE dt.document_id = $1
`

type GetTagsByDocumentIDRow struct {
	TagID      pgtype.UUID `json:"tag_id"`
	Attributes []byte      `json:"attributes"`
}

func (q *Queries) GetTagsByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]GetTagsByDocumentIDRow, error) {
	rows, err := q.db.Query(ctx, getTagsByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsByDocumentIDRow{}
	for rows.Next() {
		var i GetTagsByDocumentIDRow
		if err := rows.Scan(&i.TagID, &i.Attributes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagAssociation = `-- name: RemoveTagAssociation :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

func (q *Queries) RemoveTagAssociation(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTagAssociation, documentID, tagID)
	return err
}

const updateDocumentTagAttributes = `-- name: UpdateDocumentTagAttributes :exec
UPDATE document_tags SET
    attributes = $3
WHERE document_id = $1 AND tag_id = $2
`

func (q *Queries) UpdateDocumentTagAttributes(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID, attributes []byte) error {
	_, err := q.db.Exec(ctx, updateDocumentTagAttributes, documentID, tagID, attributes)
	return err
}
