// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    namespace_id,
    file_name,
    title,
    mime_type,
    checksum_sha256,
    file_size
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING 
    id,
    file_name,
    title,
    checksum_sha256,
    created_at
`

type CreateDocumentRow struct {
	ID             pgtype.UUID        `json:"id"`
	FileName       string             `json:"file_name"`
	Title          string             `json:"title"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, iD pgtype.UUID, namespaceID pgtype.UUID, fileName string, title string, mimeType string, checksumSha256 string, fileSize int64) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		iD,
		namespaceID,
		fileName,
		title,
		mimeType,
		checksumSha256,
		fileSize,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Title,
		&i.ChecksumSha256,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, namespace_id, file_name, title, document_date, mime_type, checksum_sha256, file_size, page_count, attributes, attributes_version, attributes_metadata, created_at, modified_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.FileName,
		&i.Title,
		&i.DocumentDate,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.FileSize,
		&i.PageCount,
		&i.Attributes,
		&i.AttributesVersion,
		&i.AttributesMetadata,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
    file_name = COALESCE($2, file_name),
    title = COALESCE($3, title),
    document_date = COALESCE($4, document_date),
    mime_type = COALESCE($5, mime_type),
    file_size = COALESCE($6, file_size),
    attributes = COALESCE($7, attributes),
    attributes_metadata = COALESCE($8, attributes_metadata),
    modified_at = NOW()
WHERE id = $1
RETURNING id, namespace_id, file_name, title, document_date, mime_type, checksum_sha256, file_size, page_count, attributes, attributes_version, attributes_metadata, created_at, modified_at
`

func (q *Queries) UpdateDocument(ctx context.Context, iD pgtype.UUID, fileName string, title string, documentDate pgtype.Date, mimeType string, fileSize int64, attributes []byte, attributesMetadata []byte) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		iD,
		fileName,
		title,
		documentDate,
		mimeType,
		fileSize,
		attributes,
		attributesMetadata,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.FileName,
		&i.Title,
		&i.DocumentDate,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.FileSize,
		&i.PageCount,
		&i.Attributes,
		&i.AttributesVersion,
		&i.AttributesMetadata,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
