// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document-tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id, attributes)
VALUES ($1, $2, $3)
ON CONFLICT (document_id, tag_id) DO NOTHING
`

func (q *Queries) AddDocumentTag(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID, attributes []byte) error {
	_, err := q.db.Exec(ctx, addDocumentTag, documentID, tagID, attributes)
	return err
}

const getDocumentTagAttributes = `-- name: GetDocumentTagAttributes :one

SELECT attributes, attributes_version
FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

type GetDocumentTagAttributesRow struct {
	Attributes        []byte `json:"attributes"`
	AttributesVersion *int64 `json:"attributes_version"`
}

// --------- Tag-specific attributes -----------
func (q *Queries) GetDocumentTagAttributes(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID) (GetDocumentTagAttributesRow, error) {
	row := q.db.QueryRow(ctx, getDocumentTagAttributes, documentID, tagID)
	var i GetDocumentTagAttributesRow
	err := row.Scan(&i.Attributes, &i.AttributesVersion)
	return i, err
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.namespace_id, t.name, t.path
FROM tags t
JOIN document_tags dt ON t.id = dt.tag_id
WHERE dt.document_id = $1
`

type GetDocumentTagsRow struct {
	ID          pgtype.UUID `json:"id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Name        string      `json:"name"`
	Path        string      `json:"path"`
}

func (q *Queries) GetDocumentTags(ctx context.Context, documentID pgtype.UUID) ([]GetDocumentTagsRow, error) {
	rows, err := q.db.Query(ctx, getDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentTagsRow{}
	for rows.Next() {
		var i GetDocumentTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Name,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

func (q *Queries) RemoveDocumentTag(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeDocumentTag, documentID, tagID)
	return err
}

const updateDocumentTagAttributes = `-- name: UpdateDocumentTagAttributes :exec
UPDATE document_tags
SET attributes = $3, modified_at = NOW()
WHERE document_id = $1 AND tag_id = $2
`

func (q *Queries) UpdateDocumentTagAttributes(ctx context.Context, documentID pgtype.UUID, tagID pgtype.UUID, attributes []byte) error {
	_, err := q.db.Exec(ctx, updateDocumentTagAttributes, documentID, tagID, attributes)
	return err
}
