// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttributeSchema struct {
	TagID      pgtype.UUID        `json:"tag_id"`
	Version    int64              `json:"version"`
	JsonSchema json.RawMessage    `json:"json_schema"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID                 pgtype.UUID        `json:"id"`
	NamespaceID        pgtype.UUID        `json:"namespace_id"`
	FileName           string             `json:"file_name"`
	Title              string             `json:"title"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	MimeType           string             `json:"mime_type"`
	ChecksumSha256     string             `json:"checksum_sha256"`
	FileSize           int64              `json:"file_size"`
	PageCount          *int32             `json:"page_count"`
	Attributes         []byte             `json:"attributes"`
	AttributesVersion  *int64             `json:"attributes_version"`
	AttributesMetadata []byte             `json:"attributes_metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ModifiedAt         pgtype.Timestamptz `json:"modified_at"`
}

type DocumentTag struct {
	DocumentID         pgtype.UUID        `json:"document_id"`
	TagID              pgtype.UUID        `json:"tag_id"`
	Attributes         []byte             `json:"attributes"`
	AttributesVersion  *int64             `json:"attributes_version"`
	AttributesMetadata []byte             `json:"attributes_metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ModifiedAt         pgtype.Timestamptz `json:"modified_at"`
}

type Namespace struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
}

type Tag struct {
	ID          pgtype.UUID        `json:"id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Path        string             `json:"path"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Color       *string            `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
}
