// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: namespaces.sql

package sqlc

import (
	"context"
)

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name) VALUES ($1) RETURNING id, name, created_at, modified_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespaces WHERE name = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteNamespace, name)
	return err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, name, created_at, modified_at FROM namespaces WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getNamespaces = `-- name: GetNamespaces :many
SELECT id, name, created_at, modified_at FROM namespaces ORDER BY created_at DESC
`

func (q *Queries) GetNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, getNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
