// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDocument(ctx context.Context, iD pgtype.UUID, namespaceID pgtype.UUID, fileName string, title string, mimeType string, checksumSha256 string, fileSize int64) (CreateDocumentRow, error)
	CreateNamespace(ctx context.Context, name string) (Namespace, error)
	CreateSchema(ctx context.Context, tagID pgtype.UUID, jsonSchema json.RawMessage) (AttributeSchema, error)
	CreateTag(ctx context.Context, namespaceID pgtype.UUID, name string, description *string, path string, parentID pgtype.UUID, color *string) (Tag, error)
	DeleteDocument(ctx context.Context, id pgtype.UUID) error
	DeleteNamespace(ctx context.Context, name string) error
	GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetDocumentsByChecksum(ctx context.Context, checksumSha256 string) ([]Document, error)
	GetDocumentsByNamespace(ctx context.Context, namespaceID pgtype.UUID, limit int32, offset int32) ([]Document, error)
	GetNamespaceByName(ctx context.Context, name string) (Namespace, error)
	GetNamespaces(ctx context.Context) ([]Namespace, error)
	GetSchemas(ctx context.Context) ([]AttributeSchema, error)
	UpdateDocument(ctx context.Context, iD pgtype.UUID, fileName string, title string, documentDate pgtype.Date, mimeType string, fileSize int64, attributes []byte) (Document, error)
}

var _ Querier = (*Queries)(nil)
