// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    namespace_id,
    name,
    description,
    path,
    parent_id,
    color
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, namespace_id, name, description, path, parent_id, color, created_at, modified_at
`

func (q *Queries) CreateTag(ctx context.Context, namespaceID pgtype.UUID, name string, description *string, path string, parentID pgtype.UUID, color *string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		namespaceID,
		name,
		description,
		path,
		parentID,
		color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.ParentID,
		&i.Color,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
